### ISSUE TITLE
Battery use when idle is too high

### ISSUE THREAD

**Issue by Dietr1ch** [tguillem/android-mpd#1]
Today I left the server open (paused) and it drained a third of the battery capacity (according to Android app info)

I really expect that idling results on little power usage, maybe the server could (optionally) be paused while the phone is locked if the player is stopped or paused.

**Comment by tguillem** [comment]
I just checked on a Nexus 7.
ampd use 4% of cpu when playing a mp3 and 0% when paused.

Maybe you had a large music database to scan (only one time) ?

**Comment by Dietr1ch** [comment]
I'll try to reproduce this again today, maybe I had the stay awake option on (I can't check because I installed a custom build yesterday to try a patch), which seems probably now :c

**Comment by Dietr1ch** [comment]
It seems it's either not reproducible, or the stay awake option was on and it was totally my fault.
I've just reached 35% battery capacity left and now my phone only blames it on the screen and the Mediaserver (I've had music playing all the time).
